name: "triagecat"
description: "GitHub action to automate managing repositories with labels, milestones and projects."
author: "GitHub"
inputs:
  token:
    description: "A github PAT with org:write for project board management"
    required: false
  config-path:
    description: "The path to the configuration .yml file"
    default: ".github/triagecat.yml"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
