on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Build project
        run: pnpm run build

      - name: Push build to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: build project"
