on:
  issues:
    types: [opened, closed, labeled, unlabeled, milestoned, demilestoned]
  pull_request_target:
    types: [labeled, unlabeled, opened, closed, converted_to_draft, ready_for_review]
  pull_request_review:
    types: [submitted]
# issue_comment:
#   types: [created]
  workflow_dispatch:

jobs:
  pain:
    name: Pain
    runs-on: ubuntu-latest
    steps:
      - uses: ooliver1/triagecat@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
