on:
  push:
    branches:
      - master
      - dev

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: triagecat
          pre-release: ${{ github.ref_name != 'master' }}
          token: ${{ secrets.RELEASE_TOKEN }}
